apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsq-prometheus-exporter
  namespace: default
  labels:
    app: nsq-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsq-prometheus-exporter
  template:
    metadata:
      labels:
        app: nsq-prometheus-exporter
    spec:
      containers:
      - name: nsq-prometheus-exporter
        image: vortex14/nsq-exporter:latest
        ports:
          - containerPort: 9527
            name: http
        command:
          - ./nsq-prometheus-exporter
          - -nsq.lookupd.address
          - nsqlookupd.nsq.svc.cluster.local:4161
          - --nsq.k8s.mode=true
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
          limits:
            cpu: "50m"
            memory: "75Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nsq-prometheus-exporter
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: http
  selector:
    app: nsq-prometheus-exporter