{
 "title": "NSQ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total nodes count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(nsq_node_topic_count)" }
   ]
  },
  {
   "title": "total clients count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nsq_channel_client_count)" }
   ]
  },
  {
   "title": "total topics count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(nsq_topic_message_count) by (topic))"
    }
   ]
  },
  {
   "title": "total messages count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nsq_topic_message_count)" }
   ]
  },
  {
   "title": "topic depth count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nsq_topic_depth) by (topic) > 0"
    }
   ]
  },
  {
   "title": "produce messages ops  peer topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nsq_topic_message_count[5m])) by (topic)",
     "legendFormat": "{{topic}} ops"
    }
   ]
  },
  {
   "title": "topic-channel depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nsq_channel_depth) by (topic, channel) > 0",
     "legendFormat": "{{topic}} -- {{channel}}"
    }
   ]
  },
  {
   "title": "topic's channel count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nsq_topic_channel_count) by (topic, paused) > 0"
    }
   ]
  },
  {
   "title": "node topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(nsq_node_topic_count) by (hostname, http_port, remote_address, version)"
    }
   ]
  }
 ]
}